=== scikit-hep/pyhf/src/pyhf/schemas/1.0.0/workspace.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "https://scikit-hep.org/pyhf/schemas/1.0.0/workspace.json",
    "type": "object",
    "properties": {
        "channels": { "type": "array", "items": {"$ref": "defs.json#/definitions/channel"}, "minItems": 1 },
        "measurements": { "type": "array", "items": {"$ref": "defs.json#/definitions/measurement"}, "minItems": 1 },
        "observations": { "type": "array", "items": {"$ref": "defs.json#/definitions/observation" }, "minItems": 1 },
        "version": { "const": "1.0.0" }
    },
    "additionalProperties": false,
    "required": ["channels", "measurements", "observations", "version"]
}

=== scikit-hep/pyhf/tests/test_upgrade/workspace_1.0.0.json
{
    "channels": [
        {
            "name": "singlechannel",
            "samples": [
                {
                    "data": [
                        5
                    ],
                    "modifiers": [
                        {
                            "data": null,
                            "name": "mu",
                            "type": "normfactor"
                        }
                    ],
                    "name": "signal"
                },
                {
                    "data": [
                        50
                    ],
                    "modifiers": [
                        {
                            "data": [
                                6
                            ],
                            "name": "uncorr_bkguncrt",
                            "type": "shapesys"
                        }
                    ],
                    "name": "background"
                }
            ]
        }
    ],
    "measurements": [
        {
            "config": {
                "parameters": [
                    {
                        "bounds": [
                            [
                                0,
                                10
                            ]
                        ],
                        "fixed": false,
                        "inits": [
                            1
                        ],
                        "name": "mu"
                    },
                    {
                        "bounds": [
                            [
                                1e-10,
                                10
                            ]
                        ],
                        "fixed": false,
                        "inits": [
                            1
                        ],
                        "name": "uncorr_bkguncrt"
                    }
                ],
                "poi": "mu"
            },
            "name": "measurement"
        }
    ],
    "observations": [
        {
            "data": [
                50
            ],
            "name": "singlechannel"
        }
    ],
    "version": "1.0.0"
}

=== scikit-hep/pyhf/tests/test_export/workspace_no_parameter_bounds.json
{
    "channels": [
        {
            "name": "ch",
            "samples": [
                {
                    "data": [1000.0],
                    "modifiers": [
                        {"data": null, "name": "mu_sig", "type": "normfactor"},
                        {
                            "data": {"hi": 1.5, "lo": 0.5},
                            "name": "unc",
                            "type": "normsys"
                        }
                    ],
                    "name": "signal"
                }
            ]
        }
    ],
    "measurements": [
        {
            "config": {
                "parameters": [
                    {
                        "name": "mu_sig",
                        "inits": [5]
                    }
                ],
                "poi": "mu_sig"
            },
            "name": "meas"
        }
    ],
    "observations": [{"data": [1000], "name": "ch"}],
    "version": "1.0.0"
}

=== scikit-hep/pyhf/tests/test_modifiers/issue1720_greedy_staterror.json
{
  "channels": [
    {
      "name": "channel",
      "samples": [
        {
          "data": [
            5
          ],
          "modifiers": [],
          "name": "signal"
        },
        {
          "data": [
            1
          ],
          "modifiers": [
            {
              "data": [
                1.5
              ],
              "name": "NP",
              "type": "shapesys"
            }
          ],
          "name": "bkg"
        }
      ]
    }
  ],
  "measurements": [
    {
      "config": {
        "parameters": [],
        "poi": "NP"
      },
      "name": ""
    }
  ],
  "observations": [
    {
      "data": [
        0
      ],
      "name": "channel"
    }
  ],
  "version": "1.0.0"
}

=== scikit-hep/pyhf/validation/xmlimport_input_bkg.json
{
    "channels": [
        {
            "name": "channel1",
            "samples": [
                {
                    "data": [
                        20.0,
                        10.0
                    ],
                    "modifiers": [
                        {
                            "data": {
                                "hi": 1.05,
                                "lo": 0.95
                            },
                            "name": "syst1",
                            "type": "normsys"
                        },
                        {
                            "data": null,
                            "name": "SigXsecOverSM",
                            "type": "normfactor"
                        }
                    ],
                    "name": "signal"
                },
                {
                    "data": [
                        100.0,
                        0.0
                    ],
                    "modifiers": [
                        {
                            "data": null,
                            "name": "lumi",
                            "type": "lumi"
                        },
                        {
                            "data": [
                                5.000000074505806,
                                0.0
                            ],
                            "name": "staterror_channel1",
                            "type": "staterror"
                        },
                        {
                            "data": {
                                "hi": 1.05,
                                "lo": 0.95
                            },
                            "name": "syst2",
                            "type": "normsys"
                        }
                    ],
                    "name": "background1"
                },
                {
                    "data": [
                        0.0,
                        100.0
                    ],
                    "modifiers": [
                        {
                            "data": null,
                            "name": "lumi",
                            "type": "lumi"
                        },
                        {
                            "data": [
                                0.0,
                                10.0
                            ],
                            "name": "staterror_channel1",
                            "type": "staterror"
                        },
                        {
                            "data": {
                                "hi": 1.05,
                                "lo": 0.95
                            },
                            "name": "syst3",
                            "type": "normsys"
                        }
                    ],
                    "name": "background2"
                }
            ]
        }
    ],
    "measurements": [
        {
            "config": {
                "parameters": [
                    {
                        "auxdata": [
                            1.0
                        ],
                        "bounds": [
                            [
                                0.5,
                                1.5
                            ]
                        ],
                        "fixed": true,
                        "inits": [
                            1.0
                        ],
                        "name": "lumi",
                        "sigmas": [
                            0.1
                        ]
                    },
                    {
                        "bounds": [
                            [
                                0.0,
                                3.0
                            ]
                        ],
                        "inits": [
                            1.0
                        ],
                        "name": "SigXsecOverSM"
                    },
                    {
                        "fixed": true,
                        "name": "syst1"
                    }
                ],
                "poi": "SigXsecOverSM"
            },
            "name": "GaussExample"
        }
    ],
    "observations": [
        {
            "data": [
                100.0,
                100.0
            ],
            "name": "channel1"
        }
    ],
    "version": "1.0.0"
}

=== scikit-hep/pyhf/tests/test_workspace/poiless.json
{
  "channels": [
    {
      "name": "singlechannel",
      "samples": [
        {
          "name": "signal",
          "data": [
            12,
            11
          ],
          "modifiers": [
            {
              "name": "mu",
              "type": "normfactor",
              "data": null
            }
          ]
        },
        {
          "name": "background",
          "data": [
            50,
            52
          ],
          "modifiers": [
            {
              "name": "uncorr_bkguncrt",
              "type": "shapesys",
              "data": [
                3,
                7
              ]
            }
          ]
        }
      ]
    }
  ],
  "observations": [
    {
      "name": "singlechannel",
      "data": [
        51,
        48
      ]
    }
  ],
  "measurements": [
    {
      "name": "Measurement",
      "config": {
        "poi": "",
        "parameters": []
      }
    }
  ],
  "version": "1.0.0"
}

=== scikit-hep/pyhf/examples/2-bin_1-channel.json
{
    "channels": [
        { "name": "singlechannel",
          "samples": [
            { "name": "signal",
              "data": [5.0, 10.0],
              "modifiers": [ { "name": "mu", "type": "normfactor", "data": null} ]
            },
            { "name": "background",
              "data": [50.0, 60.0],
              "modifiers": [ {"name": "uncorr_bkguncrt", "type": "shapesys", "data": [5.0, 12.0]} ]
            }
          ]
        }
    ],
    "observations": [
        { "name": "singlechannel", "data": [50.0, 60.0] }
    ],
    "measurements": [
        { "name": "Measurement", "config": {"poi": "mu", "parameters": []} }
    ],
    "version": "1.0.0"
}
